export const ROUTE_PATHS = Object.freeze({
  home: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  dashboard: '/dashboard',
  citizenDashboard: '/citizen',
  reportComplaint: '/citizen/report',
  myComplaints: '/citizen/complaints',
  nearbyComplaints: '/citizen/nearby',
  officerDashboard: '/officer',
  supervisorDashboard: '/supervisor',
  adminDashboard: '/admin',
  userManagement: '/admin/users',
  accessDenied: '/access-denied',
});
