import { useEffect, useState } from 'react';
import { getSettings, getSystemHealth, runMaintenance, updateSetting } from '../../services/adminApi.js';
import { useAuth } from '../../contexts/AuthContext.jsx';

export default function SystemHealth() {
 const { user }=useAuth(); const [health,setHealth]=useState(null); const [settings,setSettings]=useState([]); const [message,setMessage]=useState(''); const [retention,setRetention]=useState(365);
 const load=async()=>{const [h,s]=await Promise.all([getSystemHealth(),getSettings()]);setHealth(h);setSettings(s);}; useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 const save=async(setting)=>{try{await updateSetting(setting.key,{value:setting.value,description:setting.description,isPublic:setting.isPublic});setMessage(`${setting.key} updated.`);await load();}catch(e){setMessage(e.message);}};
 const maintenance=async(dryRun)=>{try{const result=await runMaintenance({dryRun,retentionDays:Number(retention)});setMessage(`${dryRun?'Preview':'Cleanup'}: ${result.expiredReadNotifications} notifications, ${result.expiredRefreshTokens} refresh tokens, ${result.expiredEmailVerificationTokens} email tokens.`);}catch(e){setMessage(e.message);}};
 return <section className="p-6 lg:p-10"><p className="text-xs font-black uppercase tracking-[0.2em] text-violet-300">Operations</p><h1 className="mt-2 text-3xl font-black text-white">System health & configuration</h1><p className="mt-2 text-slate-400">Production-readiness visibility and controlled SuperAdmin maintenance actions.</p>{message&&<div className="mt-5 rounded-xl border border-sky-400/20 bg-sky-400/10 p-3 text-sky-200">{message}</div>}
 {health&&<><div className="mt-6 grid gap-4 md:grid-cols-4"><Card label="Overall" value={health.overallStatus}/><Card label="Environment" value={health.environment}/><Card label="Version" value={health.version}/><Card label="Memory" value={`${health.managedMemoryMb} MB`}/></div><div className="mt-6 grid gap-4 md:grid-cols-3">{health.dependencies.map(x=><article key={x.name} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex justify-between"><h3 className="font-bold capitalize text-white">{x.name}</h3><span className={x.status==='Healthy'?'text-emerald-300':'text-amber-300'}>{x.status}</span></div><p className="mt-2 text-sm text-slate-400">{x.description||'Dependency check completed.'}</p><p className="mt-3 text-xs text-slate-500">{x.durationMs} ms</p></article>)}</div></>}
 <h2 className="mt-10 text-xl font-black text-white">Runtime settings</h2><div className="mt-4 space-y-3">{settings.map((x,i)=><div key={x.key} className="grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 md:grid-cols-[1fr_220px_auto]"><div><b className="text-white">{x.key}</b><p className="text-sm text-slate-400">{x.description}</p></div><input disabled={user?.role!=='SuperAdmin'} value={x.value} onChange={e=>setSettings(settings.map((s,j)=>j===i?{...s,value:e.target.value}:s))} className="rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-white disabled:opacity-50"/><button disabled={user?.role!=='SuperAdmin'} onClick={()=>save(x)} className="rounded-xl bg-violet-500 px-4 py-2 font-bold text-white disabled:opacity-40">Save</button></div>)}</div>
 <h2 className="mt-10 text-xl font-black text-white">Safe maintenance</h2><div className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5"><p className="text-sm text-amber-100">Preview cleanup first. Execution removes only archived read notifications beyond retention and clears expired authentication tokens.</p><div className="mt-4 flex flex-wrap gap-3"><input type="number" min="30" max="3650" value={retention} onChange={e=>setRetention(e.target.value)} className="w-40 rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-white"/><button onClick={()=>maintenance(true)} className="rounded-xl bg-white/10 px-4 py-2 font-bold text-white">Preview</button><button disabled={user?.role!=='SuperAdmin'} onClick={()=>maintenance(false)} className="rounded-xl bg-rose-500 px-4 py-2 font-bold text-white disabled:opacity-40">Run cleanup</button></div></div>
 </section>;
}
function Card({label,value}){return <article className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-xl font-black text-white">{value}</p></article>}
