
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext.jsx';
import { securityApi } from '../../services/securityApi.js';
const formatDate = (value) => value ? new Date(value).toLocaleString() : 'Not available';

export default function AccountSecurity() {
  const [session, setSession] = useState(null); const [twoFactor, setTwoFactor] = useState(null); const [setup, setSetup] = useState(null); const [code, setCode] = useState(''); const [recoveryCodes, setRecoveryCodes] = useState([]); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState('');
  const { logout } = useAuth(); const navigate = useNavigate();
  const load = async () => { try { const [nextSession, nextTwoFactor] = await Promise.all([securityApi.getSession(), securityApi.getTwoFactorStatus()]); setSession(nextSession); setTwoFactor(nextTwoFactor); } catch (reason) { setError(reason.message || 'Unable to load security information.'); } };
  useEffect(() => { load(); }, []);
  const finishAndSignOut = async (text) => { setMessage(text); setTimeout(async () => { try { await logout(); } finally { navigate('/login', { replace: true }); } }, 1200); };
  const beginSetup = async () => { setBusy('setup'); setError(''); try { setSetup(await securityApi.beginTwoFactorSetup()); setMessage('Add the manual key to Google Authenticator, Microsoft Authenticator or another TOTP app.'); } catch (reason) { setError(reason.message); } finally { setBusy(''); } };
  const enable = async () => { setBusy('enable'); setError(''); try { const result = await securityApi.enableTwoFactor(code); setRecoveryCodes(result.recoveryCodes || []); setTwoFactor({ enabled: true }); setSetup(null); setCode(''); setMessage('2FA enabled. Save the recovery codes, then sign in again.'); } catch (reason) { setError(reason.message); } finally { setBusy(''); } };
  const disable = async () => { setBusy('disable'); setError(''); try { await securityApi.disableTwoFactor(code); await finishAndSignOut('2FA disabled. Signing you out…'); } catch (reason) { setError(reason.message); setBusy(''); } };
  const revoke = async () => { if (!window.confirm('Revoke every active session, including this browser?')) return; setBusy('revoke'); try { await securityApi.revokeMySessions(); await finishAndSignOut('Sessions revoked. Signing out…'); } catch (reason) { setError(reason.message); setBusy(''); } };
  return <section className="mx-auto max-w-5xl space-y-6 p-6"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-sky-400">Account protection</p><h2 className="mt-2 text-3xl font-black text-white">Security & sessions</h2><p className="mt-2 text-slate-400">Manage your session and authenticator-based two-factor authentication.</p></div>
    {error && <div className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-200">{error}</div>}{message && <div className="rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-emerald-200">{message}</div>}
    {session && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[['Account', session.email], ['Role', session.role], ['Last login', formatDate(session.lastLoginAtUtc)], ['Access token expires', formatDate(session.accessTokenExpiresAtUtc)], ['Refresh session expires', formatDate(session.refreshSessionExpiresAtUtc)], ['Authorization version', session.authorizationVersion]].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 break-words font-semibold text-white">{value}</p></div>)}</div>}
    <div className="rounded-2xl border border-sky-400/20 bg-sky-400/5 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold text-white">Authenticator two-factor authentication</h3><p className="mt-2 text-sm text-slate-400">Status: <strong className="text-white">{twoFactor?.enabled ? 'Enabled' : twoFactor?.setupPending ? 'Setup pending' : 'Disabled'}</strong></p></div>{!twoFactor?.enabled && <button disabled={busy} onClick={beginSetup} className="rounded-xl bg-sky-500 px-5 py-3 font-bold text-white">Start setup</button>}</div>
      {setup && <div className="mt-5 rounded-xl border border-white/10 bg-slate-950/50 p-4"><p className="text-sm text-slate-400">Manual entry key</p><code className="mt-2 block break-all text-lg font-bold tracking-widest text-sky-200">{setup.manualEntryKey}</code><p className="mt-3 break-all text-xs text-slate-500">{setup.otpAuthUri}</p></div>}
      {(setup || twoFactor?.enabled) && <div className="mt-5 flex flex-wrap gap-3"><input value={code} onChange={(e) => setCode(e.target.value)} placeholder="6-digit or recovery code" className="input max-w-xs" />{setup && <button disabled={busy || !code} onClick={enable} className="rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">Confirm and enable</button>}{twoFactor?.enabled && <button disabled={busy || !code} onClick={disable} className="rounded-xl bg-rose-500 px-5 py-3 font-bold text-white">Disable 2FA</button>}</div>}
      {recoveryCodes.length > 0 && <div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4"><p className="font-bold text-amber-200">Save these one-time recovery codes now</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{recoveryCodes.map((item) => <code key={item} className="rounded bg-slate-950/70 p-2 text-center text-white">{item}</code>)}</div></div>}
    </div>
    <div className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-6"><h3 className="text-lg font-bold text-white">Emergency sign-out</h3><p className="mt-2 text-sm text-slate-400">Invalidate the current access token and refresh session on every device.</p><button disabled={busy} onClick={revoke} className="mt-5 rounded-xl bg-rose-500 px-5 py-3 font-bold text-white disabled:opacity-60">Revoke all sessions</button></div>
  </section>;
}
