import { useEffect,useState } from "react";
import { AccountCircle, AlternateEmail, BadgeOutlined, PhoneOutlined, SaveOutlined } from "@mui/icons-material";
import { Avatar, Box, Button, Card, CardContent, Chip, InputAdornment, TextField, Typography } from "@mui/material";
import { useMutation,useQuery } from "@tanstack/react-query";
import { userApi } from "../../api/userApi";
import useAuth from "../../hooks/useAuth";
import PageHeader from "../../components/common/PageHeader";
import { notify } from "../../utils/notify";
export default function ProfilePage(){const{user,refreshUser}=useAuth();const{data}=useQuery({queryKey:["profile"],queryFn:userApi.profile});const[value,setValue]=useState({fullName:"",phone:""});useEffect(()=>{const profile=data||user;setValue({fullName:profile?.fullName||"",phone:profile?.phone||""})},[data,user]);const mutation=useMutation({mutationFn:()=>userApi.updateProfile(value),onSuccess:()=>{notify("Profile updated");refreshUser()},onError:()=>notify("Profile update failed","error")});const profile=data||user||{};return <><PageHeader title="Profile and identity" description="Manage the verified details connected to your CivicHero account."/><div className="grid gap-5 lg:grid-cols-[320px_1fr]"><Card className="overflow-hidden"><Box className="h-28 bg-gradient-to-r from-blueberry-700 to-blueberry-600"/><CardContent className="text-center" sx={{p:4,pt:0}}><Avatar sx={{width:92,height:92,mx:"auto",mt:-6,border:"6px solid white",bgcolor:"secondary.main",color:"text.primary",fontSize:34,fontWeight:900}}>{profile.fullName?.[0]||"U"}</Avatar><Typography variant="h5" sx={{mt:2}}>{profile.fullName}</Typography><Typography color="text.secondary">{profile.email}</Typography><Chip icon={<BadgeOutlined/>} color="primary" variant="outlined" label={profile.role||"Citizen"} sx={{mt:2}}/><Typography variant="body2" color="text.secondary" sx={{mt:2}}>{profile.departmentName||profile.wardName||"Citizen community account"}</Typography></CardContent></Card><Card><CardContent sx={{p:{xs:3,md:5}}}><Typography variant="h5">Personal information</Typography><Typography color="text.secondary" sx={{mb:4}}>Keep these details current so important updates reach you.</Typography><div className="grid gap-4 md:grid-cols-2"><TextField label="Full name" value={value.fullName} onChange={e=>setValue({...value,fullName:e.target.value})} InputProps={{startAdornment:<InputAdornment position="start"><AccountCircle/></InputAdornment>}}/><TextField label="Phone number" value={value.phone} onChange={e=>setValue({...value,phone:e.target.value})} InputProps={{startAdornment:<InputAdornment position="start"><PhoneOutlined/></InputAdornment>}}/><TextField disabled label="Verified email" value={profile.email||""} InputProps={{startAdornment:<InputAdornment position="start"><AlternateEmail/></InputAdornment>}}/><TextField disabled label="Account role" value={profile.role||""} InputProps={{startAdornment:<InputAdornment position="start"><BadgeOutlined/></InputAdornment>}}/></div><Button variant="contained" startIcon={<SaveOutlined/>} sx={{mt:4}} disabled={mutation.isPending||value.fullName.trim().length<2} onClick={()=>mutation.mutate()}>Save profile</Button></CardContent></Card></div></>}
