import { useState } from 'react';
import { notificationApi } from '../../services/notificationApi.js';

export default function BroadcastNotifications() {
  const [form, setForm] = useState({ title:'', message:'', role:'', actionUrl:'' });
  const [status, setStatus] = useState('');
  const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); setError(''); setStatus(''); try { const result = await notificationApi.broadcast({ ...form, role: form.role || null, actionUrl: form.actionUrl || null }); setStatus(`Broadcast created for ${result.recipients} active users.`); setForm({ title:'',message:'',role:'',actionUrl:'' }); } catch (reason) { setError(reason.message); } };
  return <section className="p-6 lg:p-10"><p className="text-sm font-bold uppercase tracking-wider text-sky-300">Administrative communication</p><h2 className="mt-2 text-3xl font-black text-white">Broadcast notification</h2><p className="mt-2 text-slate-400">Send a real-time in-app alert to every active user or one role.</p>{error && <Alert tone="error">{error}</Alert>}{status && <Alert>{status}</Alert>}<form onSubmit={submit} className="mt-8 max-w-3xl space-y-5 rounded-2xl border border-white/10 bg-white/5 p-7"><Field label="Title"><input required maxLength={200} value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} className="input" /></Field><Field label="Audience"><select value={form.role} onChange={(e)=>setForm({...form,role:e.target.value})} className="input"><option value="">All active users</option><option>Citizen</option><option>Officer</option><option>Supervisor</option><option>Admin</option><option>SuperAdmin</option></select></Field><Field label="Message"><textarea required rows={6} maxLength={2000} value={form.message} onChange={(e)=>setForm({...form,message:e.target.value})} className="input" /></Field><Field label="Optional action URL"><input placeholder="/citizen/complaints" value={form.actionUrl} onChange={(e)=>setForm({...form,actionUrl:e.target.value})} className="input" /></Field><button className="rounded-xl bg-sky-500 px-6 py-3 font-black text-white hover:bg-sky-400">Send broadcast</button></form><style>{`.input{margin-top:.5rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.12);background:#0f172a;padding:.8rem 1rem;color:white}.input:focus{outline:2px solid #38bdf8}`}</style></section>;
}
function Field({label,children}){return <label className="block text-sm font-bold text-slate-300">{label}{children}</label>}
function Alert({children,tone='success'}){return <div className={`mt-5 rounded-xl border p-4 ${tone==='error'?'border-rose-400/30 bg-rose-400/10 text-rose-100':'border-emerald-400/30 bg-emerald-400/10 text-emerald-100'}`}>{children}</div>}
