import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Pagination from '../../components/common/Pagination.jsx';
import SlaBadge from '../../components/common/SlaBadge.jsx';
import { assignmentApi } from '../../services/assignmentApi.js';

export default function AssignmentQueue() {
  const [filters, setFilters] = useState({ page: 1, pageSize: 12, priority: '', search: '' }); const [result, setResult] = useState({ items: [], page: 1, totalPages: 0 }); const [workload, setWorkload] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); Promise.all([assignmentApi.pending(filters), assignmentApi.workload()]).then(([queue, officers]) => { setResult(queue); setWorkload(officers); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); };
  useEffect(() => { const timer = setTimeout(load, 200); return () => clearTimeout(timer); }, [filters]);
  return <section className="p-6 lg:p-10"><h2 className="text-3xl font-black text-white">Assignment queue</h2><p className="mt-2 text-slate-400">Assign new complaints and recover rejected work.</p><div className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4 md:grid-cols-[1fr_220px]"><input className="input mt-0" value={filters.search} onChange={(e) => setFilters((x) => ({ ...x, search: e.target.value, page: 1 }))} placeholder="Search complaint" /><select className="input mt-0" value={filters.priority} onChange={(e) => setFilters((x) => ({ ...x, priority: e.target.value, page: 1 }))}><option value="">All priorities</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></div>{error && <div className="mt-6 rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-100">{error}</div>}<div className="mt-8 grid gap-7 xl:grid-cols-[1.4fr_.8fr]"><div>{loading ? <p className="text-slate-400">Loading queue…</p> : result.items.length ? <div className="space-y-4">{result.items.map((item) => <article key={item.complaintId} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-mono text-xs text-sky-300">{item.referenceNumber}</span><SlaBadge state={item.slaState} remainingMinutes={item.remainingMinutes} /></div><h3 className="mt-3 text-xl font-black text-white">{item.title}</h3><p className="mt-2 text-sm text-slate-400">{item.departmentName} · {item.wardName} · {item.priority}</p><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-500">{item.complaintStatus}</span><Link to={`/supervisor/assignments/${item.complaintId}`} className="rounded-lg bg-amber-500 px-4 py-2 text-sm font-black text-slate-950">Assign officer</Link></div></article>)}</div> : <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-8 text-slate-400">No complaints currently need assignment.</div>}<Pagination page={result.page} totalPages={result.totalPages} onPageChange={(page) => setFilters((x) => ({ ...x, page }))} /></div><aside className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><h3 className="text-lg font-black text-white">Officer workload</h3><p className="mt-1 text-sm text-slate-500">Lowest active workload first</p><div className="mt-5 space-y-3">{workload.slice(0, 8).map((officer) => <div key={officer.officerId} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between"><b className="text-sm text-white">{officer.officerName}</b><span className="text-xs text-sky-300">{officer.activeWorkload} active</span></div><p className="mt-1 text-xs text-slate-500">{officer.wardName || 'No ward'} · {officer.overdueCount} overdue</p></div>)}</div></aside></div></section>;
}
