import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import AssignmentCard from '../../components/common/AssignmentCard.jsx';
import MetricCard from '../../components/common/MetricCard.jsx';
import { assignmentApi } from '../../services/assignmentApi.js';

export default function SupervisorDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { assignmentApi.supervisorDashboard().then(setData).catch((reason) => setError(reason.message)); }, []);
  return <section className="p-6 lg:p-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-amber-300">Operations control</p><h2 className="mt-2 text-4xl font-black text-white">Supervisor overview</h2><p className="mt-2 text-slate-400">Balance officer workload and protect assignment and resolution SLAs.</p></div><Link to="/supervisor/assignments" className="rounded-xl bg-amber-500 px-5 py-3 font-black text-slate-950">Manage assignment queue</Link></div>{error && <div className="mt-6 rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-100">{error}</div>}{!data ? <p className="mt-8 text-slate-400">Loading operations dashboard…</p> : <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Unassigned" value={data.unassigned} hint={`${data.reassignmentPending} need reassignment`} tone="amber" /><MetricCard label="In progress" value={data.inProgress} hint={`${data.pending} awaiting acceptance`} /><MetricCard label="Completed this week" value={data.completedThisWeek} hint={`${data.slaCompliancePercent}% SLA compliance`} tone="emerald" /><MetricCard label="Overdue" value={data.overdue} hint="Requires intervention" tone="rose" /></div><div className="mt-10 flex items-center justify-between"><h3 className="text-2xl font-black text-white">Highest SLA risk</h3><Link to="/supervisor/overdue" className="text-sm font-bold text-rose-300">View overdue →</Link></div>{data.priorityItems.length ? <div className="mt-5 grid gap-5 xl:grid-cols-2">{data.priorityItems.map((item) => <AssignmentCard key={item.complaintId} item={item} basePath="/supervisor/assignments" actionLabel="Manage" />)}</div> : <div className="mt-5 rounded-2xl border border-white/10 bg-white/[0.04] p-8 text-slate-400">No active assignment risk.</div>}</>}</section>;
}
