import { useEffect, useRef, useState } from "react";
import { Close, Login, OpenInNew, Send, SmartToy } from "@mui/icons-material";
import { Avatar, Box, Chip, CircularProgress, Fab, IconButton, Paper, TextField, Tooltip, Typography } from "@mui/material";
import { useMutation } from "@tanstack/react-query";
import { Link } from "react-router";
import { chatbotApi } from "../../api/chatbotApi";
import useAuth from "../../hooks/useAuth";

const welcome = { sender: "Assistant", content: "Namaste! I’m your CivicHero guide. I can help you report an issue, track progress, or understand civic services." };
export default function ChatbotWidget(){
  const { isAuthenticated } = useAuth();
  const [open,setOpen]=useState(false),[sessionId,setSessionId]=useState(""),[text,setText]=useState(""),[messages,setMessages]=useState([welcome]);
  const endRef = useRef(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, open]);
  const send=useMutation({mutationFn:async()=>{let id=sessionId;if(!id){const session=await chatbotApi.start();id=session.sessionId;setSessionId(id)}const message=text.trim();setMessages((items)=>[...items,{sender:"User",content:message}]);setText("");return chatbotApi.send(id,message)},onSuccess:reply=>setMessages((items)=>[...items,reply.assistantMessage||{sender:"Assistant",content:reply.message||"I’m here to help."}]),onError:()=>setMessages((items)=>[...items,{sender:"Assistant",content:"I couldn’t reach the assistant service. You can still use the quick links below."}])});
  const submit = () => { if (text.trim() && isAuthenticated && !send.isPending) send.mutate(); };
  return <div className="fixed bottom-5 right-5 z-[1500]">{open&&<Paper elevation={18} className="chat-panel mb-3 flex h-[min(590px,calc(100vh-110px))] w-[min(400px,calc(100vw-28px))] flex-col overflow-hidden rounded-[26px]"><header className="bg-gradient-to-r from-blueberry-700 to-blueberry-600 p-4 text-white"><div className="flex items-center"><Avatar sx={{ bgcolor: "secondary.main", color: "text.primary", mr: 1.5 }}><SmartToy /></Avatar><div className="grow"><Typography fontWeight={900}>CivicHero Assistant</Typography><Typography variant="caption" sx={{ opacity: .72 }}>Civic guidance · AI assisted</Typography></div><IconButton color="inherit" onClick={()=>setOpen(false)} aria-label="Close assistant"><Close/></IconButton></div></header><div className="grow space-y-3 overflow-y-auto bg-[#f8f9ff] p-4">{messages.map((message,index)=><div key={`${message.sender}-${index}`} className={`chat-bubble max-w-[88%] rounded-2xl p-3 ${message.sender==="User"?"ml-auto rounded-br-sm bg-blueberry-600 text-white":"rounded-bl-sm border border-civic-border bg-white"}`}><Typography variant="body2" sx={{ lineHeight: 1.55 }}>{message.content}</Typography></div>)}{send.isPending&&<div className="flex w-fit items-center gap-2 rounded-2xl bg-white p-3"><CircularProgress size={16}/><Typography variant="caption">Thinking…</Typography></div>}<div ref={endRef}/></div>{!isAuthenticated&&<Box className="border-t bg-cream-200 p-3"><Typography variant="body2" fontWeight={700}>Sign in for personalized complaint help.</Typography><div className="mt-2 flex flex-wrap gap-2"><Chip component={Link} clickable to="/report-anonymously" icon={<OpenInNew/>} label="Anonymous report"/><Chip component={Link} clickable to="/track-anonymous" label="Track privately"/><Chip component={Link} clickable to="/login" color="primary" icon={<Login/>} label="Sign in"/></div></Box>}<div className="flex gap-1 border-t bg-white p-2"><TextField fullWidth size="small" disabled={!isAuthenticated} placeholder={isAuthenticated?"Ask about civic services":"Sign in to chat"} value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();submit()}}}/><IconButton color="primary" disabled={!isAuthenticated||!text.trim()||send.isPending} onClick={submit}><Send/></IconButton></div></Paper>}<Tooltip title={open?"Close CivicHero assistant":"Ask CivicHero"} placement="left"><Fab color="secondary" size="large" aria-label="Open chatbot" onClick={()=>setOpen((value)=>!value)} sx={{ boxShadow:"0 14px 34px rgba(38,55,130,.28)" }}><SmartToy/></Fab></Tooltip></div>;
}
