namespace CivicHero.Backend.Core.Enums;

/// <summary>
/// Identifies who sent a chat message.
/// Used by the chat system and AI chatbot.
/// </summary>
public enum MessageSender
{
    /// <summary>
    /// Message sent by a citizen.
    /// </summary>
    Citizen = 1,

    /// <summary>
    /// Message sent by a government officer.
    /// </summary>
    Officer = 2,

    /// <summary>
    /// Message generated by the AI chatbot.
    /// </summary>
    Chatbot = 3,

    /// <summary>
    /// System-generated message.
    /// </summary>
    System = 4
}