import { useEffect, useState } from 'react';
import { disputeApi } from '../../services/disputeApi.js';

export default function AppealManagement() {
  const [items, setItems] = useState([]); const [remarks, setRemarks] = useState({}); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = async () => { try { setError(''); setItems(await disputeApi.queue(true)); } catch (e) { setError(e.message || 'Unable to load appeals.'); } };
  useEffect(() => { load(); }, []);
  const decide = async (id, decision) => { const note = (remarks[id] || '').trim(); if (note.length < 10) { setError('Enter decision remarks of at least 10 characters.'); return; } setBusy(`${id}-${decision}`); try { await disputeApi.adminDecision(id, { decision, remarks: note }); await load(); } catch (e) { setError(e.errors?.join(' ') || e.message || 'Decision failed.'); } finally { setBusy(''); } };
  return <section className="space-y-5 p-6 lg:p-10"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-sky-400">Final review</p><h2 className="mt-2 text-3xl font-black text-white">Appeal management</h2><p className="mt-2 text-slate-400">Citizen appeals and disputes escalated by Supervisors appear in this queue.</p></div>{error && <p className="rounded-xl bg-rose-500/10 p-4 text-rose-200">{error}</p>}<div className="space-y-4">{items.length === 0 ? <p className="rounded-2xl border border-white/10 bg-white/5 p-6 text-slate-400">No appeals are awaiting Admin review.</p> : items.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-xs text-sky-300">{item.referenceNumber}</p><h3 className="mt-2 font-bold text-white">{item.title}</h3></div><span className="h-fit rounded-full bg-violet-400/10 px-3 py-1 text-sm text-violet-200">{item.status}</span></div><p className="mt-3 text-sm text-slate-400">{item.adminRemarks || item.citizenRemarks || 'No reason supplied.'}</p><textarea value={remarks[item.id] || ''} onChange={(e) => setRemarks((current) => ({ ...current, [item.id]: e.target.value }))} className="input mt-4 min-h-24" placeholder="Final review reason and evidence considered"/><div className="mt-4 flex flex-wrap gap-2"><button disabled={!!busy} onClick={() => decide(item.id, 'Close')} className="rounded-lg bg-emerald-500/20 px-3 py-2 text-sm font-bold text-emerald-200 disabled:opacity-40">Confirm closure</button><button disabled={!!busy} onClick={() => decide(item.id, 'Rework')} className="rounded-lg bg-amber-500/20 px-3 py-2 text-sm font-bold text-amber-200 disabled:opacity-40">Order rework</button><button disabled={!!busy} onClick={() => decide(item.id, 'Fraud')} className="rounded-lg bg-rose-500/20 px-3 py-2 text-sm font-bold text-rose-200 disabled:opacity-40">Close as fraud</button></div></article>)}</div></section>;
}
