// <auto-generated />
using System;
using CivicHero.Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CivicHero.Backend.Migrations
{
    [DbContext(typeof(CivicDbContext))]
    [Migration("20260730014657_Phase17IntegrationHardening")]
    partial class Phase17IntegrationHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AiFraudAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<float>("FraudScore")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RequiresManualReview");

                    b.HasIndex("ComplaintId", "AnalyzedAt");

                    b.ToTable("ai_fraud_analyses", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AiTriageAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ClassificationConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DuplicateComplaintId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DuplicateScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("DuplicateStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal>("FraudScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("FraudVerdict")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PredictedCategory")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long?>("PredictedDepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PredictedPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PriorityScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("RawProviderResponse")
                        .HasColumnType("longtext");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReviewDecision")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId", "AnalyzedAt");

                    b.HasIndex("RequiresManualReview", "ReviewedAt");

                    b.ToTable("ai_triage_analyses", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserRole")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Success", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("EntityName", "EntityId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "SentAt");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Complaint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("AiConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("AiRiskScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("AiSuggestedCategory")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("AiTriagedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("AssignedOfficerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DuplicateOfComplaintId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AiTriagedAt");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("DuplicateOfComplaintId");

                    b.HasIndex("WardId");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("DepartmentId", "WardId", "Status");

                    b.ToTable("complaints", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("AssignedById")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("AssignmentDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OfficerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("ReassignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ResolutionDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("AssignmentDueAt");

                    b.HasIndex("ResolutionDueAt");

                    b.HasIndex("ComplaintId", "IsCurrent");

                    b.HasIndex("OfficerId", "Status", "IsCurrent");

                    b.ToTable("complaint_assignments", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("complaint_categories", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsResolutionEvidence")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("S3Url")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("S3Key")
                        .IsUnique();

                    b.ToTable("complaint_images", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintProgressUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("OfficerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId", "CreatedAt");

                    b.HasIndex("OfficerId", "CreatedAt");

                    b.ToTable("complaint_progress_updates", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintTimeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ComplaintId", "Timestamp");

                    b.ToTable("complaint_timelines", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<double?>("DistanceMetres")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("SubmittedLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("SubmittedLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ComplaintId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Decision", "DueAt");

                    b.ToTable("complaint_verifications", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintVote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("VotedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ComplaintId", "UserId")
                        .IsUnique();

                    b.ToTable("complaint_votes", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Contractor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Status");

                    b.ToTable("contractors", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ROADS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Road surface, pothole and footpath complaints.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Roads & Potholes",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            Code = "WASTE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Garbage collection and illegal dumping complaints.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Solid Waste Management",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            Code = "LIGHT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Streetlight and electrical public-infrastructure complaints.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Street Lighting",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4L,
                            Code = "WATER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Water leakage, low pressure and supply complaints.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Water Supply",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5L,
                            Code = "DRAIN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Blocked drains, sewage and flooding complaints.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Drainage & Sewerage",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6L,
                            Code = "PARKS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Public garden and civic-space maintenance complaints.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parks & Public Spaces",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.DisputeAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminDecision")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<DateTimeOffset?>("AppealDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CitizenRemarks")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<long>("ComplaintId")
                        .HasColumnType("bigint");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RaisedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SupervisorDecision")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SupervisorRemarks")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.HasKey("Id");

                    b.HasIndex("RaisedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("ComplaintId", "RaisedAt");

                    b.ToTable("dispute_audit_logs", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsArchived", "CreatedAt");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.NotificationPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AssignmentUpdates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ComplaintUpdates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DisputeUpdates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InAppEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RewardUpdates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SecurityAlerts")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("VerificationUpdates")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Redemption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<string>("RedemptionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("RewardCatalogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RedemptionCode")
                        .IsUnique();

                    b.HasIndex("RewardCatalogId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("redemptions", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ReputationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PointsDelta")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("RunningBalance")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "ReferenceType", "ReferenceId", "Reason")
                        .IsUnique();

                    b.ToTable("reputation_logs", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.RewardCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "PointsCost");

                    b.ToTable("reward_catalog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Download a personalised civic participation certificate.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Civic Hero Certificate",
                            PointsCost = 250,
                            StockQuantity = 100000,
                            Type = "Certificate",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A demonstration voucher for recognised civic participation.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Public Transport Voucher",
                            PointsCost = 500,
                            StockQuantity = 500,
                            Type = "Voucher",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A digital badge for citizens who help close multiple civic issues.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Neighborhood Guardian Badge",
                            PointsCost = 750,
                            StockQuantity = 100000,
                            Type = "Badge",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A demonstration eco-friendly merchandise reward.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CivicHero Eco Kit",
                            PointsCost = 1200,
                            StockQuantity = 100,
                            Type = "Merchandise",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Premium certificate for sustained civic contribution.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Community Champion Certificate",
                            PointsCost = 2000,
                            StockQuantity = 100000,
                            Type = "Certificate",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.SystemSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Group");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AuthorizationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTimeOffset?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("RefreshTokenCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("TwoFactorEnabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwoFactorRecoveryCodesJson")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorSecretProtected")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("WardId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("WardId");

                    b.HasIndex("DepartmentId", "WardId", "Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Ward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BoundaryEast")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("BoundaryNorth")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("BoundarySouth")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("BoundaryWest")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("wards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BoundaryEast = 72.9900m,
                            BoundaryNorth = 19.1300m,
                            BoundarySouth = 18.8900m,
                            BoundaryWest = 72.7700m,
                            Code = "WARD-A",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ward A",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            BoundaryEast = 73.0100m,
                            BoundaryNorth = 19.1500m,
                            BoundarySouth = 18.9200m,
                            BoundaryWest = 72.7900m,
                            Code = "WARD-B",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = 2L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ward B",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            BoundaryEast = 73.0300m,
                            BoundaryNorth = 19.1700m,
                            BoundarySouth = 18.9400m,
                            BoundaryWest = 72.8100m,
                            Code = "WARD-C",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = 3L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ward C",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4L,
                            BoundaryEast = 73.0500m,
                            BoundaryNorth = 19.1900m,
                            BoundarySouth = 18.9600m,
                            BoundaryWest = 72.8300m,
                            Code = "WARD-D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = 4L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ward D",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5L,
                            BoundaryEast = 73.0700m,
                            BoundaryNorth = 19.2100m,
                            BoundarySouth = 18.9800m,
                            BoundaryWest = 72.8500m,
                            Code = "WARD-E",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = 5L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ward E",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6L,
                            BoundaryEast = 73.0900m,
                            BoundaryNorth = 19.2300m,
                            BoundarySouth = 19.0000m,
                            BoundaryWest = 72.8700m,
                            Code = "WARD-F",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = 6L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ward F",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AiFraudAnalysis", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("FraudAnalyses")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AiTriageAnalysis", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("TriageAnalyses")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatSession", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Complaint", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "AssignedOfficer")
                        .WithMany("AssignedComplaints")
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "Citizen")
                        .WithMany("CreatedComplaints")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Ward", "Ward")
                        .WithMany("Complaints")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Citizen");

                    b.Navigation("Department");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintAssignment", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "AssignedBy")
                        .WithMany("AssignmentsCreated")
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Assignments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "Officer")
                        .WithMany("OfficerAssignments")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Complaint");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintCategory", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintImage", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Images")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintProgressUpdate", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "Officer")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintTimeline", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Timeline")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Complaint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintVerification", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "Citizen")
                        .WithMany("ComplaintVerifications")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Verifications")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("VerificationOverrides")
                        .HasForeignKey("UserId");

                    b.Navigation("Citizen");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintVote", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Votes")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany("ComplaintVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Contractor", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany("Contractors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.DisputeAuditLog", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Disputes")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Complaint");

                    b.Navigation("RaisedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Notification", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.NotificationPreference", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("CivicHero.Backend.Core.Entities.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Redemption", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.RewardCatalog", "RewardCatalog")
                        .WithMany("Redemptions")
                        .HasForeignKey("RewardCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany("Redemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardCatalog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ReputationLog", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany("ReputationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.User", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CivicHero.Backend.Core.Entities.Ward", "Ward")
                        .WithMany("Users")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Ward", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany("Wards")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Complaint", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Disputes");

                    b.Navigation("FraudAnalyses");

                    b.Navigation("Images");

                    b.Navigation("ProgressUpdates");

                    b.Navigation("Timeline");

                    b.Navigation("TriageAnalyses");

                    b.Navigation("Verifications");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Contractors");

                    b.Navigation("Users");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.RewardCatalog", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.User", b =>
                {
                    b.Navigation("AssignedComplaints");

                    b.Navigation("AssignmentsCreated");

                    b.Navigation("ChatSessions");

                    b.Navigation("ComplaintVerifications");

                    b.Navigation("ComplaintVotes");

                    b.Navigation("CreatedComplaints");

                    b.Navigation("NotificationPreference");

                    b.Navigation("Notifications");

                    b.Navigation("OfficerAssignments");

                    b.Navigation("ProgressUpdates");

                    b.Navigation("Redemptions");

                    b.Navigation("ReputationLogs");

                    b.Navigation("VerificationOverrides");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Ward", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
