// <auto-generated />
using System;
using CivicHero.Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CivicHero.Backend.Migrations
{
    [DbContext(typeof(CivicDbContext))]
    partial class CivicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AiFraudAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AnalysisSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("AnalyzedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFraudDetected")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedOnUtc");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("ConfidenceScore");

                    b.HasIndex("IsFraudDetected");

                    b.HasIndex("ComplaintId", "AnalyzedOnUtc");

                    b.HasIndex("IsFraudDetected", "ConfidenceScore");

                    b.ToTable("AiFraudAnalyses", null, t =>
                        {
                            t.HasCheckConstraint("CK_AiFraudAnalysis_ConfidenceScore", "`ConfidenceScore` >= 0 AND `ConfidenceScore` <= 1");
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentOnUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("Sender");

                    b.HasIndex("SentOnUtc");

                    b.HasIndex("ChatSessionId", "SentOnUtc");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ComplaintId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("ComplaintId", "IsActive");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContractorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContractorId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WardId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ContractorId");

                    b.HasIndex("ContractorId1");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("WardId");

                    b.HasIndex("WardId1");

                    b.HasIndex("DepartmentId", "Status");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("Complaints", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MetadataAnalyzed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("MetadataAnalyzed");

                    b.ToTable("ComplaintImages", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintTimeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("ComplaintId", "CreatedOnUtc");

                    b.ToTable("ComplaintTimelines", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("ComplaintId", "UserId")
                        .IsUnique();

                    b.ToTable("ComplaintVotes", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Contractors", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.DisputeAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("ComplaintId", "OccurredOnUtc");

                    b.HasIndex("UserId", "OccurredOnUtc");

                    b.ToTable("DisputeAuditLogs", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "CreatedOnUtc");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Redemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RewardCatalogId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RedeemedOnUtc");

                    b.HasIndex("RewardCatalogId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("RewardCatalogId", "Status");

                    b.HasIndex("UserId", "RedeemedOnUtc");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Redemptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Redemption_PointsSpent", "`PointsSpent` > 0");
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ReputationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("Points");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "CreatedOnUtc");

                    b.ToTable("ReputationLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReputationLog_Points", "Points <> 0");
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.RewardCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RequiredPoints");

                    b.HasIndex("Type");

                    b.HasIndex("IsActive", "RequiredPoints");

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("RewardCatalogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_RewardCatalog_RequiredPoints", "`RequiredPoints` > 0");
                        });
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("WardId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("WardId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Wards", (string)null);
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.AiFraudAnalysis", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("FraudAnalyses")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ChatSession", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany()
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId1");

                    b.Navigation("Complaint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Complaint", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CivicHero.Backend.Core.Entities.Contractor", null)
                        .WithMany("Complaints")
                        .HasForeignKey("ContractorId1");

                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Department", null)
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId1");

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("Complaints")
                        .HasForeignKey("UserId");

                    b.HasOne("CivicHero.Backend.Core.Entities.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Ward", null)
                        .WithMany("Complaints")
                        .HasForeignKey("WardId1");

                    b.OwnsOne("CivicHero.Backend.Core.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("ComplaintId")
                                .HasColumnType("char(36)");

                            b1.Property<double>("Latitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("double")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("double")
                                .HasColumnName("Longitude");

                            b1.HasKey("ComplaintId");

                            b1.ToTable("Complaints");

                            b1.WithOwner()
                                .HasForeignKey("ComplaintId");
                        });

                    b.Navigation("Citizen");

                    b.Navigation("Contractor");

                    b.Navigation("Department");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintImage", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Images")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintTimeline", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ComplaintVote", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany("Votes")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("ComplaintVotes")
                        .HasForeignKey("UserId1");

                    b.Navigation("Complaint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Contractor", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.Department", null)
                        .WithMany("Contractors")
                        .HasForeignKey("DepartmentId1");

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CivicHero.Backend.Core.Entities.Contractor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.DisputeAuditLog", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Complaint", "Complaint")
                        .WithMany()
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("DisputeAuditLogs")
                        .HasForeignKey("UserId1");

                    b.Navigation("Complaint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Notification", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Redemption", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.RewardCatalog", "RewardCatalog")
                        .WithMany()
                        .HasForeignKey("RewardCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("Redemptions")
                        .HasForeignKey("UserId1");

                    b.Navigation("RewardCatalog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.ReputationLog", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicHero.Backend.Core.Entities.User", null)
                        .WithMany("ReputationLogs")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.User", b =>
                {
                    b.HasOne("CivicHero.Backend.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CivicHero.Backend.Core.Entities.Department", null)
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId1");

                    b.HasOne("CivicHero.Backend.Core.Entities.Ward", null)
                        .WithMany("Users")
                        .HasForeignKey("WardId");

                    b.OwnsOne("CivicHero.Backend.Core.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Department");

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Complaint", b =>
                {
                    b.Navigation("FraudAnalyses");

                    b.Navigation("Images");

                    b.Navigation("TimelineEntries");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Contractor", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Contractors");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("ComplaintVotes");

                    b.Navigation("Complaints");

                    b.Navigation("DisputeAuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Redemptions");

                    b.Navigation("ReputationLogs");
                });

            modelBuilder.Entity("CivicHero.Backend.Core.Entities.Ward", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
