import { useEffect, useState } from 'react';
import { commentApi } from '../../services/commentApi.js';
export default function CommentModerationQueue() {
  const [data,setData]=useState({items:[]}); const [status,setStatus]=useState('Hidden'); const [search,setSearch]=useState(''); const [error,setError]=useState('');
  const load=async()=>{try{setData(await commentApi.moderationQueue({status,search,page:1,pageSize:50}));setError('');}catch(e){setError(e.message);}};
  useEffect(()=>{load();},[status]);
  const moderate=async(item,decision)=>{const reason=prompt(`Reason for ${decision.toLowerCase()}:`,'Moderator review')||'';try{await commentApi.moderate(item.complaintId,item.id,{decision,reason});await load();}catch(e){setError(e.errors?.join(' ')||e.message);}};
  return <section className="p-6 lg:p-10"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-3xl font-black text-white">Comment moderation</h2><p className="mt-2 text-slate-400">Review public comments held by automated screening and manage visibility within your scope.</p></div><div className="flex flex-wrap gap-2"><input className="input max-w-xs" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search comment or complaint"/><button onClick={load} className="rounded-xl bg-sky-500 px-4 py-2 font-black text-white">Search</button><select className="input max-w-40" value={status} onChange={e=>setStatus(e.target.value)}><option>Hidden</option><option>Visible</option><option>Removed</option><option value="">All</option></select></div></div>{error&&<p className="mt-5 rounded-xl bg-rose-500/10 p-4 text-rose-100">{error}</p>}<div className="mt-6 space-y-4">{data.items?.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-sm text-sky-300">{item.referenceNumber}</p><h3 className="font-black text-white">{item.complaintTitle}</h3><p className="text-sm text-slate-500">{item.departmentName} · {item.wardName} · {item.authorName} ({item.authorRole})</p></div><span className="h-fit rounded-full bg-amber-400/10 px-3 py-1 text-sm font-bold text-amber-200">{item.moderationStatus}</span></div><p className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-950/50 p-4 text-slate-300">{item.body}</p>{item.moderationReason&&<p className="mt-2 text-sm text-amber-200">Reason: {item.moderationReason}</p>}<div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>moderate(item,'Visible')} className="rounded-xl bg-emerald-500 px-4 py-2 font-black text-white">Approve</button><button onClick={()=>moderate(item,'Hidden')} className="rounded-xl border border-amber-400/30 px-4 py-2 font-bold text-amber-200">Hide</button><button onClick={()=>moderate(item,'Removed')} className="rounded-xl bg-rose-500 px-4 py-2 font-black text-white">Remove</button></div></article>)}{!data.items?.length&&<p className="rounded-2xl border border-white/10 p-8 text-center text-slate-500">No comments match this filter.</p>}</div></section>;
}
