import { useEffect, useState } from 'react';
import BarChart from '../../components/charts/BarChart.jsx';
import MetricCard from '../../components/common/MetricCard.jsx';
import { analyticsApi } from '../../services/analyticsApi.js';

export default function TeamAnalytics() {
  const [data,setData] = useState(null); const [error,setError] = useState('');
  useEffect(()=>{ Promise.all([analyticsApi.overview(),analyticsApi.officers(),analyticsApi.wards(),analyticsApi.sla()]).then(([overview,officers,wards,sla])=>setData({overview,officers,wards,sla})).catch(e=>setError(e.message)); },[]);
  return <section className="p-6 lg:p-10"><p className="text-sm font-bold uppercase tracking-[.16em] text-emerald-300">Department scope</p><h2 className="mt-2 text-3xl font-black text-white">Team performance</h2><p className="mt-2 text-slate-400">Only your department’s complaints, officers and wards are included.</p>{error && <p className="mt-6 rounded-xl bg-rose-400/10 p-4 text-rose-100">{error}</p>}{!data?<p className="mt-8 text-slate-400">Loading team analytics…</p>:<><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Open complaints" value={data.overview.openComplaints}/><MetricCard label="Resolution rate" value={`${data.overview.resolutionRate}%`}/><MetricCard label="SLA compliance" value={`${data.sla.overallComplianceRate}%`}/><MetricCard label="Overdue" value={data.sla.currentlyOverdue}/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Officer completion"><BarChart data={data.officers.slice(0,10)} labelKey="officerName" valueKey="completed" /></Panel><Panel title="Ward heat score"><BarChart data={data.wards.slice(0,10)} labelKey="wardName" valueKey="heatScore" /></Panel></div><Panel title="Officer scorecard"><div className="overflow-x-auto"><table className="mt-4 min-w-full text-sm"><thead className="text-left text-xs uppercase text-slate-500"><tr><th>Officer</th><th>Assigned</th><th>Active</th><th>Completed</th><th>SLA</th><th>Revisit</th></tr></thead><tbody className="divide-y divide-white/10">{data.officers.map(row=><tr key={row.officerId}><td className="py-3 font-semibold text-white">{row.officerName}<small className="block text-slate-500">{row.wardName || 'All wards'}</small></td><td>{row.assigned}</td><td>{row.active}</td><td>{row.completed}</td><td>{row.slaCompliance}%</td><td>{row.revisitRate}%</td></tr>)}</tbody></table></div></Panel></>}</section>;
}
function Panel({title,children}) { return <article className="mt-6 rounded-3xl border border-white/10 bg-white/[.04] p-6"><h3 className="text-lg font-black text-white">{title}</h3><div className="mt-5">{children}</div></article>; }
