import { useState } from "react";
import { AutoAwesome, ChevronRight, FactCheckOutlined } from "@mui/icons-material";
import { Box, Card, CardContent, Chip, LinearProgress, TextField, Typography } from "@mui/material";
import { useMutation,useQuery } from "@tanstack/react-query";
import { staffApi } from "../../../api/staffApi";
import EmptyState from "../../../components/common/EmptyState";
import PageHeader from "../../../components/common/PageHeader";
import { notify } from "../../../utils/notify";
import AIImageVerificationPanel from "../components/AIImageVerificationPanel";
const decisions={Confirm:"ConfirmEvidence",CorrectCategory:"DismissFlag",ImageUnclear:"DismissFlag",RequestMoreInfo:"RequestRework",Reject:"RequestRework"};
export default function VisualReviewPage(){const[selected,setSelected]=useState(null),[notes,setNotes]=useState("Reviewed against before and after evidence.");const{data=[],refetch}=useQuery({queryKey:["visual-review"],queryFn:()=>staffApi.visualQueue({reviewRequiredOnly:true,pageSize:50})});const review=useMutation({mutationFn:action=>staffApi.reviewAnalysis(selected.id,{decision:decisions[action],notes}),onSuccess:()=>{notify("Human visual review recorded");setSelected(null);refetch()},onError:error=>notify(error.response?.data?.message||"Review failed","error")});const items=data.items||data;return <><PageHeader title="Manual AI image review" description="Compare evidence, inspect model confidence, and record the required human decision." action={<Chip icon={<AutoAwesome/>} label={`${items.length} awaiting review`} color="primary"/>}/>{items.length?<div className="stagger-grid grid gap-4 lg:grid-cols-2">{items.map(item=>{const confidence=Math.round(item.overallConfidence*100);return <Card key={item.id} onClick={()=>setSelected(item)} className="cursor-pointer hover:-translate-y-1"><CardContent sx={{p:3}}><div className="flex items-start gap-3"><Box className="feature-icon"><FactCheckOutlined/></Box><div className="min-w-0 grow"><Typography variant="h6">{item.referenceNumber} · {item.complaintTitle}</Typography><div className="mt-2 flex gap-2"><Chip size="small" label={item.verdict}/><Chip size="small" color={confidence>=80?"success":"warning"} label={`${confidence}% confidence`}/></div></div><ChevronRight color="action"/></div><Typography color="text.secondary" sx={{mt:2}}>{item.reasoning}</Typography><LinearProgress variant="determinate" value={confidence} sx={{mt:2,height:7,borderRadius:8}}/></CardContent></Card>})}</div>:<EmptyState title="No analyses require review" description="AI-flagged evidence will appear here for an authorized human decision."/>}{selected&&<div className="mt-5 space-y-3 reveal-up"><TextField fullWidth multiline minRows={2} label="Required review notes" value={notes} onChange={event=>setNotes(event.target.value)}/><AIImageVerificationPanel analysis={{...selected,confidence:selected.overallConfidence,predictedCategory:selected.verdict}} onAction={action=>notes.trim().length>=5&&review.mutate(action)}/></div>}</>}
