import PropTypes from "prop-types";
import { Assessment, Business, Category, Dashboard, Description, Groups, History, Map, Notifications, Person, Public, ReportProblem } from "@mui/icons-material";
import { Box, Drawer, List, ListItemButton, ListItemIcon, ListItemText, Toolbar, Typography } from "@mui/material";
import { useTranslation } from "react-i18next";
import { useLocation, useNavigate } from "react-router";
import useAuth from "../../hooks/useAuth";
const menus={Citizen:[["/citizen/dashboard","dashboard",Dashboard],["/community","Community",Public],["/report-complaint","reportComplaint",ReportProblem],["/my-complaints","myComplaints",Description],["/verify-resolutions","Verify resolutions",History],["/disputes","Disputes",ReportProblem],["/rewards","Rewards",Assessment],["/leaderboard","Leaderboard",Groups],["/notifications","notifications",Notifications],["/profile","profile",Person]],Staff:[["/staff/dashboard","dashboard",Dashboard],["/staff/complaints","complaints",Description],["/staff/map","heatMap",Map],["/staff/visual-review","AI image review",History],["/staff/notifications","notifications",Notifications],["/staff/profile","profile",Person]],Admin:[["/admin/dashboard","dashboard",Dashboard],["/admin/complaints","complaints",Description],["/admin/users","users",Groups],["/admin/staff","staff",Person],["/admin/departments","departments",Business],["/admin/categories","categories",Category],["/admin/wards","Wards",Map],["/admin/reports","reports",Assessment],["/admin/heat-map","heatMap",Map],["/admin/visual-review","AI image review",History],["/admin/audit-logs","auditLogs",History],["/admin/profile","profile",Person]]};
export default function Sidebar({open,onClose,desktop}){const{user}=useAuth();const{t}=useTranslation();const nav=useNavigate(),location=useLocation();const content=<><Toolbar/><Box sx={{px:2,py:2}}><Typography variant="overline" color="primary">{user?.role} workspace</Typography><Typography variant="body2" color="text.secondary" noWrap>{user?.fullName}</Typography></Box><List sx={{p:1.25}}>{(menus[user?.role]||[]).map(([path,label,Icon])=><ListItemButton key={path} selected={location.pathname===path} onClick={()=>{nav(path);onClose()}} sx={{borderRadius:3,mb:.5,minHeight:46,"&.Mui-selected":{bgcolor:"primary.light",color:"primary.dark","& .MuiListItemIcon-root":{color:"primary.main"}}}}><ListItemIcon><Icon/></ListItemIcon><ListItemText primary={t(label)}/></ListItemButton>)}</List></>;return <Drawer variant={desktop?"permanent":"temporary"} open={desktop||open} onClose={onClose} ModalProps={{keepMounted:true}} sx={{width:270,flexShrink:0,"& .MuiDrawer-paper":{width:270,boxSizing:"border-box",borderRight:"1px solid #E4E7EC",background:"rgba(255,255,255,.94)"}}}>{content}</Drawer>}
Sidebar.propTypes={open:PropTypes.bool,onClose:PropTypes.func.isRequired,desktop:PropTypes.bool};
