import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { assignmentApi } from '../../services/assignmentApi.js';

export default function UploadResolution() {
  const { complaintId } = useParams(); const navigate = useNavigate();
  const [notes, setNotes] = useState(''); const [evidence, setEvidence] = useState([]); const [location, setLocation] = useState({ latitude: '', longitude: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const capture = () => navigator.geolocation?.getCurrentPosition((position) => setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }), () => setError('Location could not be captured. You may submit evidence without GPS.'));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await assignmentApi.complete(complaintId, { notes, evidence, ...location }); navigate(`/officer/assignments/${complaintId}`, { replace: true }); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  return <section className="p-6 lg:p-10"><button onClick={() => navigate(-1)} className="text-sm font-bold text-sky-300">← Back</button><div className="mx-auto mt-5 max-w-3xl rounded-3xl border border-white/10 bg-white/[0.04] p-7"><p className="text-sm font-black uppercase tracking-widest text-emerald-300">Resolution evidence</p><h2 className="mt-2 text-3xl font-black text-white">Complete assignment</h2><p className="mt-2 text-slate-400">Upload clear after-work photos. The complaint will move to citizen verification.</p><form onSubmit={submit} className="mt-7"><label className="text-sm font-bold text-slate-300">Resolution notes</label><textarea className="input min-h-36" required minLength="10" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Describe the work completed, materials used, and final condition." /><label className="mt-5 block text-sm font-bold text-slate-300">After-work images (1–5)</label><input className="input" type="file" accept="image/jpeg,image/png,image/webp" multiple required onChange={(e) => setEvidence(Array.from(e.target.files || []).slice(0, 5))} /><p className="mt-2 text-xs text-slate-500">JPEG, PNG or WebP; maximum 5 MB each.</p><div className="mt-5 rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between"><div><b className="text-sm text-white">Completion GPS</b><p className="text-xs text-slate-500">Optional field evidence location</p></div><button type="button" onClick={capture} className="rounded-lg bg-white/10 px-3 py-2 text-xs font-black text-white">Capture location</button></div>{location.latitude && <p className="mt-3 font-mono text-xs text-emerald-300">{Number(location.latitude).toFixed(6)}, {Number(location.longitude).toFixed(6)}</p>}</div>{error && <div className="mt-5 rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-100">{error}</div>}<button disabled={busy || evidence.length < 1} className="mt-6 w-full rounded-xl bg-emerald-500 px-5 py-3 font-black text-white disabled:opacity-40">{busy ? 'Uploading evidence…' : 'Submit resolution for verification'}</button></form></div></section>;
}
