import { useEffect, useState } from 'react';
import { exportAuditLogs, getAuditLogs } from '../../services/adminApi.js';

export default function AuditLogs() {
  const [filters, setFilters] = useState({ search:'', success:'', page:1, pageSize:25 }); const [data, setData] = useState({ items:[], totalCount:0, page:1, pageSize:25 }); const [error,setError]=useState('');
  const load = async () => { try { setData(await getAuditLogs({ ...filters, success: filters.success === '' ? undefined : filters.success })); } catch(e){ setError(e.message); } };
  useEffect(()=>{ load(); },[filters.page, filters.success]);
  const download = async () => { const blob = await exportAuditLogs(filters); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='civichero-audit.csv'; a.click(); URL.revokeObjectURL(url); };
  return <section className="p-6 lg:p-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-violet-300">Immutable history</p><h1 className="mt-2 text-3xl font-black text-white">Audit logs</h1><p className="mt-2 text-slate-400">Trace every mutating API action with user, role, endpoint, result and correlation ID.</p></div><button onClick={download} className="rounded-xl bg-violet-500 px-4 py-2 font-bold text-white">Export CSV</button></div>
    <div className="mt-6 grid gap-3 md:grid-cols-[1fr_180px_auto]"><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Search user, action, entity or correlation ID" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white"/><select value={filters.success} onChange={e=>setFilters({...filters,success:e.target.value,page:1})} className="rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-white"><option value="">All results</option><option value="true">Successful</option><option value="false">Failed</option></select><button onClick={()=>{setFilters({...filters,page:1});load();}} className="rounded-xl bg-sky-500 px-5 py-3 font-bold text-white">Search</button></div>{error&&<p className="mt-4 text-rose-300">{error}</p>}
    <div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="bg-white/5 text-slate-400"><tr><th className="p-4">Time</th><th>User</th><th>Action</th><th>Entity</th><th>Result</th><th>Correlation</th></tr></thead><tbody>{data.items.map(x=><tr key={x.id} className="border-t border-white/10 text-slate-300"><td className="p-4">{new Date(x.createdAt).toLocaleString()}</td><td><b className="text-white">{x.userEmail||'System'}</b><br/><span className="text-xs">{x.userRole||'Background'}</span></td><td>{x.action}</td><td>{x.entityName}{x.entityId ? ` #${x.entityId}`:''}</td><td><span className={x.success?'text-emerald-300':'text-rose-300'}>{x.success?'Success':'Failed'} · {x.httpStatusCode}</span></td><td className="font-mono text-xs">{x.correlationId||'—'}</td></tr>)}</tbody></table></div>
    <div className="mt-4 flex items-center justify-between text-sm text-slate-400"><span>{data.totalCount} events</span><div className="flex gap-2"><button disabled={filters.page<=1} onClick={()=>setFilters({...filters,page:filters.page-1})} className="rounded-lg bg-white/5 px-3 py-2 disabled:opacity-40">Previous</button><span className="px-2 py-2">Page {filters.page}</span><button disabled={filters.page*filters.pageSize>=data.totalCount} onClick={()=>setFilters({...filters,page:filters.page+1})} className="rounded-lg bg-white/5 px-3 py-2 disabled:opacity-40">Next</button></div></div>
  </section>;
}
