import { useState } from "react";
import { GavelOutlined, History, Replay } from "@mui/icons-material";
import { Box,Button,Card,CardContent,Dialog,DialogActions,DialogContent,DialogTitle,TextField,Typography } from "@mui/material";
import { useMutation,useQuery } from "@tanstack/react-query";
import { disputeApi } from "../../api/disputeApi";
import EmptyState from "../../components/common/EmptyState";
import PageHeader from "../../components/common/PageHeader";
import StatusChip from "../../components/common/StatusChip";
import { notify } from "../../utils/notify";
export default function DisputesPage(){const[appeal,setAppeal]=useState(null),[remarks,setRemarks]=useState("");const{data=[],refetch}=useQuery({queryKey:["disputes","mine"],queryFn:disputeApi.mine});const mutation=useMutation({mutationFn:()=>disputeApi.appeal(appeal.id,remarks),onSuccess:()=>{notify("Appeal submitted");setAppeal(null);refetch()}});const items=data.items||data;return <><PageHeader title="Disputes and appeals" description="Track contested outcomes and review the complete decision history."/>{items.length?<div className="stagger-grid grid gap-4 md:grid-cols-2">{items.map(item=><Card key={item.id} className="overflow-hidden hover:-translate-y-1"><Box className="flex items-center justify-between bg-[#f8f9fc] px-4 py-3"><div className="flex items-center gap-2"><GavelOutlined color="primary"/><Typography fontWeight={900}>{item.referenceNumber||`Dispute #${item.id}`}</Typography></div><StatusChip status={item.status}/></Box><CardContent className="space-y-3" sx={{p:3}}><Typography variant="h6">{item.title}</Typography><Typography color="text.secondary">{item.citizenRemarks}</Typography><div className="rounded-2xl bg-cream-200 p-3"><Typography variant="caption">SUPERVISOR DECISION</Typography><Typography fontWeight={800}>{item.supervisorDecision||"Pending review"}</Typography></div>{item.canAppeal&&<Button startIcon={<Replay/>} variant="outlined" onClick={()=>setAppeal(item)}>Raise appeal</Button>}</CardContent></Card>)}</div>:<EmptyState title="No disputes" description="If you reject a resolution or contest a decision, its review will appear here."/>}<Dialog open={!!appeal} onClose={()=>setAppeal(null)}><DialogTitle className="flex items-center gap-2"><History color="primary"/>Appeal dispute decision</DialogTitle><DialogContent><Typography color="text.secondary" sx={{mb:2}}>Explain what evidence or context should be reconsidered.</Typography><TextField autoFocus fullWidth multiline minRows={4} label="Appeal reason" value={remarks} onChange={event=>setRemarks(event.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setAppeal(null)}>Cancel</Button><Button variant="contained" disabled={remarks.trim().length<10} onClick={()=>mutation.mutate()}>Submit appeal</Button></DialogActions></Dialog></>}
