import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import SlaBadge from '../../components/common/SlaBadge.jsx';
import StatusBadge from '../../components/common/StatusBadge.jsx';
import { assignmentApi } from '../../services/assignmentApi.js';

export default function AssignmentDetails() {
  const { complaintId } = useParams(); const navigate = useNavigate();
  const [item, setItem] = useState(null); const [message, setMessage] = useState(''); const [progress, setProgress] = useState(25); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => assignmentApi.getByComplaintId(complaintId).then(setItem).catch((reason) => setError(reason.message));
  useEffect(load, [complaintId]);
  const run = async (action) => { setBusy(true); setError(''); try { await action(); await load(); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  const reject = () => { const reason = window.prompt('Reason for rejecting this assignment:'); if (reason) run(() => assignmentApi.reject(complaintId, reason)); };
  const addProgress = () => run(async () => { await assignmentApi.progress(complaintId, { message, progressPercent: Number(progress) }); setMessage(''); });
  if (!item) return <section className="p-6 lg:p-10 text-slate-400">{error || 'Loading assignment…'}</section>;
  return <section className="p-6 lg:p-10"><button onClick={() => navigate(-1)} className="text-sm font-bold text-sky-300">← Back to queue</button>
    <div className="mt-5 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-mono text-sm text-sky-300">{item.referenceNumber}</span><SlaBadge state={item.slaState} remainingMinutes={item.remainingMinutes} /></div><div className="mt-4 flex gap-2"><StatusBadge status={item.complaintStatus} /><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold text-slate-300">{item.priority}</span></div><h2 className="mt-5 text-3xl font-black text-white">{item.title}</h2><p className="mt-3 leading-7 text-slate-300">{item.description}</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Citizen" value={item.citizenName} /><Info label="Category" value={item.category} /><Info label="Department" value={item.departmentName} /><Info label="Ward" value={item.wardName} /><Info label="Address" value={item.address} /><Info label="Assignment state" value={item.assignmentStatus} /></div>
      <div className="mt-7 flex flex-wrap gap-3">{item.canAccept && <button disabled={busy} onClick={() => run(() => assignmentApi.accept(complaintId))} className="rounded-xl bg-emerald-500 px-5 py-3 font-black text-white">Accept assignment</button>}{item.canReject && <button disabled={busy} onClick={reject} className="rounded-xl bg-rose-500 px-5 py-3 font-black text-white">Reject</button>}{item.canComplete && <Link to={`/officer/assignments/${complaintId}/resolve`} className="rounded-xl bg-sky-500 px-5 py-3 font-black text-white">Submit resolution</Link>}</div>{error && <div className="mt-5 rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-100">{error}</div>}</div>
      <aside className="space-y-6"><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><h3 className="text-lg font-black text-white">Add progress</h3><p className="mt-1 text-sm text-slate-400">Available after accepting the assignment.</p><textarea className="input min-h-28" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Site inspection, crew status, materials…" disabled={!item.canAddProgress} /><label className="mt-4 block text-xs font-bold text-slate-400">Progress: {progress}%</label><input className="mt-2 w-full" type="range" min="1" max="99" value={progress} onChange={(e) => setProgress(e.target.value)} disabled={!item.canAddProgress} /><button disabled={!item.canAddProgress || !message.trim() || busy} onClick={addProgress} className="mt-4 w-full rounded-xl bg-white/10 px-4 py-3 font-black text-white disabled:opacity-40">Save progress</button></section>
      <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><h3 className="text-lg font-black text-white">Activity</h3><div className="mt-4 space-y-4">{item.progressUpdates.length ? item.progressUpdates.map((update) => <div key={update.id} className="border-l-2 border-sky-400/40 pl-4"><div className="flex justify-between gap-3"><b className="text-sm text-white">{update.progressPercent}% · {update.officerName}</b><time className="text-xs text-slate-500">{new Date(update.createdAt).toLocaleString()}</time></div><p className="mt-1 text-sm text-slate-400">{update.message}</p></div>) : <p className="text-sm text-slate-500">No field updates yet.</p>}</div></section></aside></div>
  </section>;
}
function Info({ label, value }) { return <div><p className="text-xs font-black uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm text-slate-200">{value || '—'}</p></div>; }
