import PropTypes from "prop-types";
import { ArrowForward, ImageOutlined, LocationOnOutlined, ThumbUpAltOutlined } from "@mui/icons-material";
import { Box, Button, Card, CardActions, CardContent, Typography } from "@mui/material";
import { Link } from "react-router";
import StatusChip from "../../../components/common/StatusChip";
import PriorityChip from "../../../components/common/PriorityChip";
import { formatDate } from "../../../utils/dateFormatter";
export default function ComplaintCard({complaint,basePath="/complaints"}){const image=complaint.thumbnailUrl||complaint.images?.[0]?.url||complaint.images?.[0]?.downloadUrl;return <Card className="group flex h-full flex-col overflow-hidden hover:-translate-y-1 hover:shadow-xl">{image?<img src={image} alt="" className="h-40 w-full object-cover transition duration-500 group-hover:scale-[1.03]"/>:<Box className="grid h-32 place-items-center bg-gradient-to-br from-blueberry-50 to-cream-200 text-blueberry-600"><ImageOutlined sx={{fontSize:44,opacity:.65}}/></Box>}<CardContent className="grow space-y-3" sx={{p:3}}><div className="flex flex-wrap justify-between gap-2"><StatusChip status={complaint.status}/><PriorityChip priority={complaint.priority}/></div><Typography variant="h6" sx={{lineHeight:1.3}}>{complaint.title}</Typography><Typography variant="caption" color="text.secondary">{complaint.referenceNumber||`CH-${complaint.id}`} · {formatDate(complaint.createdAt)}</Typography><Typography color="text.secondary" sx={{display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{complaint.description}</Typography>{complaint.address&&<Typography variant="body2" className="flex items-center gap-1" color="text.secondary"><LocationOnOutlined fontSize="small"/>{complaint.address}</Typography>}</CardContent><CardActions sx={{px:3,pb:2.5,justifyContent:"space-between"}}><Typography variant="caption" className="flex items-center gap-1" color="text.secondary"><ThumbUpAltOutlined fontSize="small"/>{complaint.upvoteCount||complaint.voteCount||0}</Typography><Button component={Link} to={`${basePath}/${complaint.id}`} endIcon={<ArrowForward/>}>View details</Button></CardActions></Card>}
ComplaintCard.propTypes={complaint:PropTypes.object.isRequired,basePath:PropTypes.string};
