import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { assignmentApi } from '../../services/assignmentApi.js';

export default function EscalationHistory() {
  const [filters, setFilters] = useState({ search: '', category: '', wardId: '', fromDate: '', toDate: '' }); const [items, setItems] = useState([]); const [error, setError] = useState('');
  const load = async () => { try { setError(''); const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== '')); if (params.toDate) params.toDate = `${params.toDate}T23:59:59Z`; setItems(await assignmentApi.escalationHistory(params)); } catch (e) { setError(e.message); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [JSON.stringify(filters)]);
  return <section className="p-6 lg:p-10"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-rose-300">Operational audit</p><h2 className="mt-2 text-3xl font-black text-white">Escalation history</h2><p className="mt-2 text-slate-400">Manual escalation, SLA escalation, resumed work, rework and SuperAdmin escalation events.</p></div><div className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4 md:grid-cols-2 xl:grid-cols-5"><input className="input mt-0" value={filters.search} onChange={(e) => setFilters((x) => ({ ...x, search: e.target.value }))} placeholder="Search title or reason"/><input className="input mt-0" value={filters.category} onChange={(e) => setFilters((x) => ({ ...x, category: e.target.value }))} placeholder="Category"/><input className="input mt-0" type="number" value={filters.wardId} onChange={(e) => setFilters((x) => ({ ...x, wardId: e.target.value }))} placeholder="Ward / zone ID"/><input className="input mt-0" type="date" value={filters.fromDate} onChange={(e) => setFilters((x) => ({ ...x, fromDate: e.target.value }))}/><input className="input mt-0" type="date" value={filters.toDate} onChange={(e) => setFilters((x) => ({ ...x, toDate: e.target.value }))}/></div>{error && <p className="mt-5 rounded-xl bg-rose-500/10 p-4 text-rose-100">{error}</p>}<div className="mt-6 space-y-3">{items.map((item) => <article key={item.timelineId} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap justify-between gap-3"><div><Link className="font-mono text-xs text-sky-300" to={`/supervisor/assignments/${item.complaintId}`}>{item.referenceNumber}</Link><h3 className="mt-2 font-black text-white">{item.title}</h3></div><span className="h-fit rounded-full bg-rose-400/10 px-3 py-1 text-xs font-bold text-rose-200">{item.eventType}</span></div><p className="mt-3 text-sm text-slate-300">{item.description}</p><p className="mt-3 text-xs text-slate-500">{item.actorName || 'System'} · {new Date(item.timestamp).toLocaleString()}</p></article>)}{!items.length && <p className="rounded-2xl border border-white/10 p-8 text-center text-slate-500">No escalation events match these filters.</p>}</div></section>;
}
