import { useEffect, useState } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router-dom';
import { anonymousComplaintApi } from '../../services/anonymousComplaintApi.js';
import { ROUTE_PATHS } from '../../routes/routePaths.js';

export default function AnonymousTrackPage() {
  const [params] = useSearchParams();
  const location = useLocation();
  const initialReference = params.get('reference') || '';
  const [form, setForm] = useState({ referenceNumber: initialReference, token: location.state?.trackingToken || '' });
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const track = async (event) => { event?.preventDefault(); setLoading(true); setError(''); try { const result = await anonymousComplaintApi.track(form.referenceNumber, form.token); setData(result); } catch (e) { setError(e.message); setData(null); } finally { setLoading(false); } };
  useEffect(() => { if (form.referenceNumber && form.token) track(); }, []);
  return <section className="mx-auto max-w-3xl px-6 py-14"><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-7"><h1 className="text-3xl font-black text-white">Track an anonymous complaint</h1><p className="mt-2 text-slate-400">Both the reference and private token are required. No personal identity is exposed.</p><form onSubmit={track} className="mt-6 grid gap-4 md:grid-cols-[1fr_2fr_auto]"><input className="input" value={form.referenceNumber} onChange={(e) => setForm({ ...form, referenceNumber: e.target.value })} placeholder="CH-2026-000123" required /><input className="input font-mono" value={form.token} onChange={(e) => setForm({ ...form, token: e.target.value })} placeholder="Tracking token" required /><button disabled={loading} className="rounded-xl bg-sky-500 px-5 py-3 font-black text-white">{loading ? 'Loading…' : 'Track'}</button></form>{error && <p className="mt-5 rounded-xl bg-rose-500/10 p-4 text-rose-100">{error}</p>}{data && <article className="mt-7 space-y-6"><div className="rounded-2xl border border-sky-400/20 bg-sky-400/5 p-5"><p className="font-mono text-sm text-sky-300">{data.referenceNumber}</p><h2 className="mt-2 text-2xl font-black text-white">{data.title}</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Status" value={data.status} /><Info label="Priority" value={data.priority} /><Info label="Department" value={data.departmentName} /><Info label="Ward" value={data.wardName} /></div>{data.possibleEmergency && <p className="mt-4 rounded-lg bg-amber-400/10 p-3 text-amber-100">Emergency review: {data.emergencyReviewStatus}</p>}<p className="mt-4 text-sm text-slate-400">Contact: {data.contactHint}</p></div><section className="rounded-2xl border border-white/10 p-5"><h3 className="font-black text-white">Public progress timeline</h3><ol className="mt-4 space-y-4">{data.timeline.map((item, i) => <li key={`${item.timestamp}-${i}`} className="border-l-2 border-sky-400/30 pl-4"><div className="flex justify-between gap-3"><strong className="text-white">{item.eventType}</strong><time className="text-xs text-slate-500">{new Date(item.timestamp).toLocaleString()}</time></div><p className="mt-1 text-sm text-slate-400">{item.description}</p></li>)}</ol></section></article>}<div className="mt-6 flex gap-4 text-sm"><Link className="font-bold text-emerald-300" to={ROUTE_PATHS.anonymousReport}>Submit another anonymous complaint</Link><Link className="font-bold text-sky-300" to={ROUTE_PATHS.login}>Login</Link></div></div></section>;
}
function Info({ label, value }) { return <div><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 font-semibold text-white">{value}</p></div>; }
